name: CI

on:
  push:
    branches:
      - master
      - dev_**

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up node environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: build source
        run: |
          npm install gitbook-cli@2.2.0 -g
          gitbook install
          gitbook build
      - name: deploy
        run: |
          git config --global user.email "alick97@outlook.com"
          git config --global user.name "ci"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout --orphan gh-pages
          git rm --cached -r .
          git clean -df
          rm -rf *~
          echo "*~" >> .gitignore
          echo "_book" >> .gitignore
          git add .gitignore
          git commit -m "Ignore some files"
          cp -r _book/* .
          git add .
          git commit -m "Publish book"
          git push -f origin HEAD:gh-pages
        
